# Generated by Django 6.0.5 on 2026-05-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="paynow_poll_url",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="paynow_reference",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="project",
            name="ai_optimized_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="references_and_awards",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="template_choice",
            field=models.CharField(
                choices=[
                    ("classic", "Classic ATS"),
                    ("meridian", "Meridian (Two-Column)"),
                    ("monolith", "Monolith (Brutalist)"),
                    ("vivant", "Vivant (Elegant)"),
                ],
                default="classic",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="full_name",
            field=models.CharField(max_length=255),
        ),
    ]
