# Generated by Django 6.0.5 on 2026-05-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0002_remove_resume_paynow_poll_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
