# Generated by Django 6.0.5 on 2026-05-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0003_resume_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                    ("P", "Prefer not to say"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
